use schemars::schema_for;
use std::path::Path;
use ts_rs::TS;
fn lift_definitions(
    value: &mut serde_json::Value,
    definitions: &mut serde_json::Map<String, serde_json::Value>,
) {
    match value {
        serde_json::Value::Object(object) => {
            if let Some(serde_json::Value::Object(defs)) = object.remove("$defs") {
                for (key, mut schema) in defs {
                    lift_definitions(&mut schema, definitions);
                    if let Some(previous) = definitions.insert(key, schema.clone()) {
                        assert_eq!(previous, schema, "schema name collision");
                    }
                }
            }
            if let Some(serde_json::Value::String(reference)) = object.get_mut("$ref") {
                if let Some(name) = reference.strip_prefix("#/$defs/") {
                    *reference = format!("#/components/schemas/{name}");
                }
            }
            for child in object.values_mut() {
                lift_definitions(child, definitions);
            }
        }
        serde_json::Value::Array(array) => {
            for child in array {
                lift_definitions(child, definitions);
            }
        }
        _ => {}
    }
}
fn main() {
    let dest = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "contracts/generated".into());
    let dir = Path::new(&dest);
    std::fs::create_dir_all(dir).expect("schema output directory");
    macro_rules! emit {
        ($name:literal,$ty:ty) => {
            std::fs::write(
                dir.join(concat!($name, ".schema.json")),
                serde_json::to_string_pretty(&schema_for!($ty)).unwrap() + "\n",
            )
            .unwrap();
        };
    }
    emit!("core-request", limeos_contracts::CoreRequest);
    emit!("core-response", limeos_contracts::CoreResponse);
    emit!("executor-request", limeos_executor_protocol::Request);
    emit!("executor-ceiling", limeos_executor_protocol::Ceiling);
    emit!("intent", limeos_domain::Intent);
    emit!("event", limeos_domain::Event);
    emit!("overview", limeos_contracts::Overview);
    emit!("resource-page", limeos_contracts::ResourcePage);
    emit!("metric-history", limeos_contracts::MetricHistory);
    let mut types = String::from("// Generated by limeos-schema. Do not edit.\n");
    macro_rules! ts {
        ($ty:ty) => {
            types.push_str("export ");
            types.push_str(&<$ty>::decl());
            types.push('\n');
        };
    }
    ts!(limeos_domain::ErrorCode);
    ts!(limeos_domain::Role);
    ts!(limeos_domain::Operation);
    ts!(limeos_domain::Principal);
    ts!(limeos_domain::JobState);
    ts!(limeos_domain::Intent);
    ts!(limeos_domain::EventKind);
    ts!(limeos_domain::Event);
    ts!(limeos_contracts::Login);
    ts!(limeos_contracts::Enrollment);
    ts!(limeos_contracts::Health);
    ts!(limeos_contracts::SessionView);
    ts!(limeos_contracts::ErrorEnvelope);
    ts!(limeos_contracts::CoreRequest);
    ts!(limeos_contracts::CoreResponse);
    ts!(limeos_contracts::Source);
    ts!(limeos_contracts::Availability);
    ts!(limeos_contracts::Freshness);
    ts!(limeos_contracts::HostMetrics);
    ts!(limeos_contracts::ResourceKind);
    ts!(limeos_contracts::Resource);
    ts!(limeos_contracts::ObservationBatch);
    ts!(limeos_contracts::Overview);
    ts!(limeos_contracts::ResourcePage);
    ts!(limeos_contracts::HistoryRange);
    ts!(limeos_contracts::MetricPoint);
    ts!(limeos_contracts::MetricHistory);
    ts!(limeos_executor_protocol::Request);
    ts!(limeos_executor_protocol::Ceiling);
    std::fs::write(dir.join("types.ts"), types).unwrap();
    let mut openapi = serde_json::json!({"openapi":"3.1.0","info":{"title":"LimeOS foundation API","version":"1"},"paths":{
        "/api/v1/health":{"get":{"responses":{"200":{"description":"Core readiness","content":{"application/json":{"schema":schema_for!(limeos_contracts::Health)}}}}}},
        "/api/v1/auth/login":{"post":{"requestBody":{"required":true,"content":{"application/json":{"schema":schema_for!(limeos_contracts::Login)}}},"responses":{"200":{"description":"Secure session cookie and CSRF token","content":{"application/json":{"schema":schema_for!(limeos_contracts::SessionView)}}},"401":{"description":"Authentication failed"}}}},
        "/api/v1/auth/session":{"get":{"responses":{"200":{"description":"Current session","content":{"application/json":{"schema":schema_for!(limeos_contracts::SessionView)}}}}}},
        "/api/v1/auth/logout":{"post":{"responses":{"204":{"description":"Session revoked"}}}}
    }});
    for (path, schema) in [
        (
            "/api/v1/overview",
            serde_json::to_value(schema_for!(limeos_contracts::Overview)).unwrap(),
        ),
        (
            "/api/v1/resources",
            serde_json::to_value(schema_for!(limeos_contracts::ResourcePage)).unwrap(),
        ),
        (
            "/api/v1/system/history",
            serde_json::to_value(schema_for!(limeos_contracts::MetricHistory)).unwrap(),
        ),
    ] {
        openapi["paths"][path] = serde_json::json!({"get":{"security":[{"session":[]}],"responses":{"200":{"description":"Scoped cached observations","content":{"application/json":{"schema":schema}}}}}});
    }
    openapi["paths"]["/api/v1/resources"]["get"]["parameters"] = serde_json::json!([
        {"name":"offset","in":"query","schema":{"type":"integer","minimum":0,"maximum":1024,"default":0}},
        {"name":"limit","in":"query","schema":{"type":"integer","minimum":1,"maximum":50,"default":20}},
        {"name":"revision","in":"query","schema":{"type":"integer","minimum":0}},
        {"name":"kind","in":"query","schema":schema_for!(limeos_contracts::ResourceKind)}
    ]);
    openapi["paths"]["/api/v1/system/history"]["get"]["parameters"] = serde_json::json!([{ "name":"range","in":"query","required":true,"schema":schema_for!(limeos_contracts::HistoryRange)}]);
    openapi["paths"]["/api/v1/observations/stream"] = serde_json::json!({"get":{"security":[{"session":[]}],"description":"Full authorized snapshot on connect and reconnect. Maximum eight readers, 25 seconds and 128 KiB per stream. Identity rechecked every five seconds.","parameters":[{"name":"Last-Event-ID","in":"header","schema":{"type":"string","pattern":"^[0-9]{1,20}$"}}],"responses":{"200":{"description":"snapshot events; id is the current revision","content":{"text/event-stream":{"schema":{"type":"string"}}}}}}});
    for path in openapi["paths"].as_object_mut().unwrap().values_mut() {
        for operation in path.as_object_mut().unwrap().values_mut() {
            for code in ["400", "401", "403", "409", "429", "503"] {
                operation["responses"][code] = serde_json::json!({
                    "description":"Structured safe error", "content":{"application/json":{"schema":schema_for!(limeos_contracts::ErrorEnvelope)}}
                });
            }
        }
    }
    openapi["paths"]["/api/v1/auth/login"]["post"]["parameters"] = serde_json::json!([
        {"name":"Origin","in":"header","required":true,"schema":{"type":"string"}}
    ]);
    openapi["paths"]["/api/v1/auth/logout"]["post"]["parameters"] = serde_json::json!([
        {"name":"Origin","in":"header","required":true,"schema":{"type":"string"}},
        {"name":"X-CSRF-Token","in":"header","required":true,"schema":{"type":"string","minLength":64,"maxLength":64}}
    ]);
    let mut definitions = serde_json::Map::new();
    lift_definitions(&mut openapi, &mut definitions);
    openapi["components"] = serde_json::json!({"schemas":definitions,"securitySchemes":{"session":{"type":"apiKey","in":"cookie","name":"__Host-limeos"}}});
    for path in ["/api/v1/auth/session", "/api/v1/auth/logout"] {
        let method = if path.ends_with("logout") {
            "post"
        } else {
            "get"
        };
        openapi["paths"][path][method]["security"] = serde_json::json!([{"session":[]}]);
    }
    std::fs::write(
        dir.join("authority-v1.sql"),
        include_str!("../../../crates/persistence/src/schema.sql"),
    )
    .unwrap();
    std::fs::write(
        dir.join("openapi.json"),
        serde_json::to_string_pretty(&openapi).unwrap() + "\n",
    )
    .unwrap();
}
