[package]
name = "limeos-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
futures-util.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tower.workspace = true
limeos-domain = { path = "../domain", version = "=0.2.0" }
limeos-contracts = { path = "../contracts", version = "=0.2.0" }

[dev-dependencies]
http-body-util.workspace = true
tokio = { workspace = true, features = ["test-util"] }
