[package]
name = "limeos-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
limeos-observations = { path = "../../crates/observations", version = "=0.2.0" }
limeos-executor-protocol = { path = "../../crates/executor-protocol", version = "=0.2.0" }
limeos-contracts = { path = "../../crates/contracts", version = "=0.2.0" }
limeos-domain = { path = "../../crates/domain", version = "=0.2.0" }
limeos-executor-container = { path = "../../crates/executor-container", version = "=0.2.0" }
tokio.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
